FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Install pnpm globally
RUN npm install -g pnpm 


COPY package.json pnpm-lock.yaml turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages


# install dependecies
RUN pnpm install

RUN pnpm add prisma@6.5.0 -D

# add a script to the global package.json that does this?
RUN pnpm run db:generate

# filter the build down to just one app?
RUN pnpm run build

CMD ["pnpm" , "run" , "start-web"]